//GET http://localhost:3000/products
###
GET http://localhost:3000/products/sale
###
GET http://localhost:3000/products/newest
###
GET http://localhost:3000/products?categoryName=broń-krótka-centralnego-zapłonu&limit=5&offset=0
###
GET http://localhost:3000/products/categories?categoryName=broń-krótka-centralnego-zapłonu
###
GET http://localhost:3000/products?categoryName=broń-długa-centralnego-zapłonu&caliber=.223REM
###
GET http://localhost:3000/products/5
###
GET http://localhost:3000/products?categoryName=broń
###
GET http://localhost:3000/products?categoryName=broń
###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "Name": "Jan",
  "LastName": "Kowalski",
  "Login": "janek123",
  "Email": "jan.kowalski@example.com",
  "Password": "SuperHaslo123!",
  "Date": "1995-01-15",
  "Adress": "Warszawa, ul. Przykładowa 10",
  "Licence": "AB1234567"
}
###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "loginOrEmail": "matixv2",
  "Password": "mati1234!"
}
###
GET http://localhost:3000/account/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBY2NvdW50SWQiOjEsImxvZ2luT3JFbWFpbCI6Im1hdGl4djIiLCJSb2xlIjoidXNlciIsImlhdCI6MTczNzI4MDA2NSwiZXhwIjoxNzM3MjgzNjY1fQ.E7-Q11orYndtTqITCVZS1qahq6PegTEp766pgs5qAyg

###
POST http://localhost:3000/products/purchase
Content-Type: application/json

{
    "AccountId": 1,
    "PaymentMethod": "Credit Card",
    "TotalCost": 199.99,
    "Products": [
        {
            "ProductId": 2,
            "Quantity": 2
        },
        {
            "ProductId": 3,
            "Quantity": 1
        }
    ]
}
###
GET http://localhost:3000/account/users
###
DELETE http://localhost:3000/account/user/6