name: Docker Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Pull MySQL image from GHCR
        run: |
          docker pull ghcr.io/bocianrocky/mysql:latest
      
      - name: Run MySQL container
        run: |
          docker run -d -p 3306:3306 ghcr.io/bocianrocky/mysql:latest
          
      - name: Stop Docker container
        run: |
          docker stop $(docker ps -q)
